services:
  db:
    image: postgres:15-alpine
    container_name: tourplanner_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tourplanner
    ports:
      - "5432:5432"
    volumes:
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tourplanner_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    container_name: tourplanner_backend
    build:
      context: ./backend    
      dockerfile: Dockerfile
    ports:
      - "5000:8080"        
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Überschreibt den ConnectionString für Docker 
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tourplanner;Username=user;Password=password
    volumes:
      - ./backend/Uploads:/app/Uploads
    depends_on:
      - db
    links:     
      - db